# Generated by Django 5.0.3 on 2024-03-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app3',
            name='content',
            field=models.CharField(max_length=255, verbose_name='Content'),
        ),
    ]
